CC=gcc

all:
	mkdir -p ../bin
	# greentext
	$(CC) greentext.c  -o ../bin/greentext
	# postref
	$(CC) postref.c    -o ../bin/postref
	# endline
	$(CC) endline.c    -o ../bin/endline

clean:
	rm ../bin/*
